### ISSUE TITLE
vimjjj 2015-05-26 Tue.

### ISSUE THREAD

**Issue by imaz** [vimjjj/log#10]
vim下手を脱却したいわたしたちのための練習会です！
オンラインチャット上でお話しつつもくもくします。
前回の様子は #9 と [idobata](https://idobata.io/organizations/vimjjj/rooms/i/join_request/48659d50-288b-4560-bacd-121081d12335) を御覧ください。
なんと3ヶ月ぶりじゃん
- 日時
  - 2015/5/26(火) 19:30〜20:30
- 場所
  - https://idobata.io/organizations/vimjjj/rooms/i/join_request/48659d50-288b-4560-bacd-121081d12335
- 内容
  - 各自好きなところでvimの練習をします
  - やることに困ったらidobataでお話することもできます

**Comment by fukajun** [comment]
何もやらなかった

これをやりたいだけだった。 <= ctags で railsのソースコードを飛び回りたい
http://qiita.com/joker1007/items/9c114a37560d6a29fe81

**Comment by cafedomancer** [comment]
Vim のヘルプ |usr_03.txt| カーソルの移動 を読みました。
03.6 から 03.8 までかな？
- スクロール
  - `CTRL-U` 半分だけ上
  - `CTRL-D` 半分だけ下
  - `CTRL-E` 1 行だけ上
  - `CTRL-Y` 1 行だけ下
  - `CTRL-F` 1 画面分だけ上 (Forward の頭文字)
  - `CTRL-B` 1 画面分だけ下 (Backward の頭文字)
- 検索
  - `/include` include を前方検索
  - `.[]^%/\?~$` はエスケープ
  - `n` 次の検索結果 (カウンタも使える)
  - `?word` word を後方検索
  - `N` 前の検索結果 (カウンタも使える)
  - `:set ignorecase` 大文字小文字を無視
  - `:set noignorecase` 上のオプションをオフ
  - `/<Up>` 検索の履歴を検索
  - `/<Down>` 検索の履歴を検索
  - `/o<Up>` o から始まる検索の履歴を検索
  - 検索ヒストリとコマンドヒストリはそれぞれ別になっている
  - `*` カーソル位置の単語を前方検索 (カウンタも使える)
  - `#` カーソル位置の単語を後方検索 (カウンタも使える)
  - `/the\>` the で終わる単語だけ検索
  - `/\<the\>` the という単語だけ検索
  - `:set hlsearch` 検索結果の強調表示
  - `:set nohlsearch` 上のオプションをオフ
  - `:nohlsearch` 強調表示だけ取り消し (オプションは切り替わらない)
  - `:set incsearch` インクリメンタルサーチ
  - `:set nowrapscan` 末尾に到達したら検索を停止

**Comment by imaz** [comment]
## やったこと
- いままでのおさらい
- 実践Vim 第1部 TIP12 「組み合わせの妙をさらに深く味わおう」の前まで

## 今日(までに)知ったこと
- `C-o` : 戻る
  - `C-n`: 戻ったトコ進む
- `:set ruler`: 現在位置を表示する
  - 右下に座標が出るようになった:smile: 
- `dap`: パラグラフ全体を消す
  - パラグラフって段落のことっぽい。超便利！
- `g~`: 大文字小文字の入れ替え
- `gu`: 小文字化、 `gU`: 大文字化
  - `g` がつくと {motion} が指定できるんだなー。
  - たとえば変数の date を定数の DATE にしたいとき、`gUaw` でできちゃう…! (あんまないけど)
- オペレーターコマンドを連続して呼び出すと現在の行に適用する
  - `>>` `<<` `==` `yy` `dd` とかよく使うけどそういう法則があったのか！
  - `g~~` で現在行の大文字小文字全部入れ替えというのができる
  - 現在行の書き換えしたい時 `cc` するといいのかぁ

#### 読んだけどよくわかんなかったこと
- `!`: {motion} で指定される行を外部プログラムを使ってフィルタリングする

## 現状確認

#### よく使うようになったもの！

##### すっかりマスター
- `:qa` 全部閉じる
- `f` `t` で行の正方向検索

##### ぎこちない
- `F` `T` で行の逆方向検索
- `.` 編集の繰り返し
- `;` 移動コマンドの繰り返し

#### 覚えてないけど使えたら便利そう
- `10<C-a>` で50が60になる
  - <C-a>にも count が使えたとは…!!
- `b` は単語の頭の後方検索
- `e` は単語末尾の後方検索
- `50%` でファイルの真ん中に移動できる

#### 使わないけど使えたら便利そう
- `,,` コメント化
- `c{motion}` で削除して挿入モード
- `aw` a word テキストオブジェクト。モーションとは違い `d` などとの組み合わせで使う

**Comment by imaz** [comment]
`,,` コメント化、デフォルトかと思ってたら .vimrc に書いてあった…

``` vim
nmap ,, <Plug>NERDCommenterToggle
vmap ,, <Plug>NERDCommenterToggle
```
