### ISSUE TITLE
vimjjj 2014-11-20 Thu.

### ISSUE THREAD

**Issue by imaz** [vimjjj/log#2]
vim下手を脱却したいわたしたちのための練習会です！
前回の様子は #1 と [idobata](https://idobata.io/organizations/vimjjj/rooms/i/join_request/48659d50-288b-4560-bacd-121081d12335) でみることができます。
- 日時
  - 2014/11/20(木) 19:30〜20:30
- 場所
  - https://idobata.io/organizations/vimjjj/rooms/i/join_request/48659d50-288b-4560-bacd-121081d12335
- 内容
  - 各自好きなところでvimの練習をします
  - やることに困ったらidobataでお話することもできます

**Comment by cafedomancer** [comment]
## やったこと

Vimスクリプト書法の「関数を使う」まで読みました。

## しったこと
- 複合コマンド(CとS)
- きょうせいギプス(http://qiita.com/ukitazume/items/619d83f2ff68fcbf966e)

## やること

次回は、Vimスクリプト書法の「関数を定義する」から読みます。

**Comment by imaz** [comment]
## やったこと
- 実践Vim P526〜

## 知ったこと
- `.` で直前のコマンドの繰り返しできる件の詳細
  - 直前の挿入モードでのキーストロークがすべて記録される!!
  - 秀丸エディタのマクロと一緒や！ これほしかったやつー！
- `A` で行の一番最後に挿入できる!!!
  - 複数行の末尾にセミコロンつけたいとき、`A;<Esc>` して `j.j.j.j.` すればいい!!! jjjj!!
- `c{motion}` で削除して挿入モード
  - `s` は `cl` の複合コマンド、1文字削除して挿入モード！

| 複合コマンド | コマンド |
| --- | --- |
| C | c$ カーソル位置から行末まで削除して挿入モード |
| S | ^C |
| I | ^i |
| A | $a |

アルファベットちがうコマンドは複合というよりそういうコマンドとして覚える気がするなあ。
cとs、CとSは複合といえばそうなんだけどそれぞれ別物と感じる。
