### ISSUE TITLE
vimjjj 2014-12-29 Mon.

### ISSUE THREAD

**Issue by imaz** [vimjjj/log#5]
vim下手を脱却したいわたしたちのための練習会です！
前回の様子は #4 と [idobata](https://idobata.io/organizations/vimjjj/rooms/i/join_request/48659d50-288b-4560-bacd-121081d12335) でみることができます。
- 日時
  - 2014/12/29(月) 17:30〜19:00
- 場所
  - https://idobata.io/organizations/vimjjj/rooms/i/join_request/48659d50-288b-4560-bacd-121081d12335
- 内容
  - 各自好きなところでvimの練習をします
  - やることに困ったらidobataでお話することもできます

**Comment by imaz** [comment]
## やったこと
- いままでのおさらい
- 実践Vim 第1章のTIP6終わりまで

## メモ
- `#` は `*` の反対
  - `*` でフォーカス一の単語検索できるお

## 今日知ったこと
- `:s` は `:substitute` だったのだなぁ
  - http://www.ksknet.net/vi/post_42.html
  - `:%s` だとファイル先頭から、 `:s` だと現在行からの置換になる
  - `:s` の後に指定した文字が区切り文字になる!!
    - `:%s,/vim,/pim,g` → `/vim` が `/pim` になった!!
    - `:s☆/vim☆/pim☆g` → `E146: Regular expressions can't be delimited by letters` ハイ

## 覚えてなかったもので習得したいもの
- `,,` コメント化!!!
- `:qa` 開いてるの全部閉じる
- `F` `T` で行の逆方向検索できる
- `I` いちばんまえに挿入
- `A` いちばんうしろに挿入
- `c{motion}` で削除して挿入モード

**Comment by myokoym** [comment]
vim のカーソル操作を学ぶゲームをやりました。
- http://phi-jp.github.io/hjkl/
- https://github.com/phi-jp/hjkl

**Comment by niku** [comment]
emacs から irb に触れる inf-ruby という拡張があります．
inf-ruby の機能を利用して pry を触れるようになっていたので，その設定をしました．

`(setq inf-ruby-default-implementation "pry")`
