### ISSUE TITLE
2014 jjj

### ISSUE THREAD

**Issue by imaz** [vimjjj/log#6]
2014年のことを振り返って思ったことを書くスレです。

**Comment by imaz** [comment]
今年のハイライト
![2014-12-29 17 39 25](https://cloud.githubusercontent.com/assets/908031/5567172/d50ec168-8f81-11e4-8a4a-b912845dc20f.png)
色んな手のものが混じっていた

**Comment by hmsk** [comment]
![screen shot 2014-12-29 at 5 53 54 pm](https://cloud.githubusercontent.com/assets/85887/5567233/b3d9e30e-8f83-11e4-830a-aacd8819af83.png)

**Comment by imaz** [comment]
- オンラインでよかった
- 1hでよかった
  - 集中力の限界
- 1〜2週に1回くらいのペースでできるとよい
